version: "3"
services:
    api:
        build: .
        depends_on:
            - mongo
        environment:
            - DB_URI=mongodb://mongo:27017/nodejsapi
            - JWT_SECRET=adfkjanionoqwidianvisdosdnf
            - CACHE_KEY=asdknieonvewodiosndvnowe
            - SWAGGER_DOC=swaggerDEV
            - ENV=production
            - PORT=5000
            - APPLICATION_NAME=NodeJsApi
        ports:
            - "5000:5000"
    
    mongo:
        image: mongo